"""Init database tables

Revision ID: d1b54fe3e34e
Revises: 
Create Date: 2026-09-11 18:44:18.972131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b54fe3e34e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_ban', sa.Integer(), nullable=False),
    sa.Column('suc_chua', sa.Integer(), nullable=False),
    sa.Column('dang_co_khach', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ban_so_ban'), ['so_ban'], unique=True)

    op.create_table('mon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_mon', sa.String(length=20), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('nhom', sa.String(length=50), nullable=False),
    sa.Column('gia', sa.Integer(), nullable=False),
    sa.Column('con_ban', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mon_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mon_ma_mon'), ['ma_mon'], unique=True)

    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau_bam', sa.String(length=255), nullable=False),
    sa.Column('vai_tro', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_dung_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'), ['ten_dang_nhap'], unique=True)

    op.create_table('hoa_don',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ban_id', sa.Integer(), nullable=False),
    sa.Column('gio_mo', sa.DateTime(), nullable=False),
    sa.Column('gio_dong', sa.DateTime(), nullable=True),
    sa.Column('tong_tien', sa.Integer(), nullable=False),
    sa.Column('da_thanh_toan', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ban_id'], ['ban.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hoa_don', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hoa_don_id'), ['id'], unique=False)

    op.create_table('chi_tiet_hoa_don',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoa_don_id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('don_gia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hoa_don_id'], ['hoa_don.id'], ),
    sa.ForeignKeyConstraint(['mon_id'], ['mon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_hoa_don', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_hoa_don_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_tiet_hoa_don', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_hoa_don_id'))

    op.drop_table('chi_tiet_hoa_don')
    with op.batch_alter_table('hoa_don', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hoa_don_id'))

    op.drop_table('hoa_don')
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_id'))

    op.drop_table('nguoi_dung')
    with op.batch_alter_table('mon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mon_ma_mon'))
        batch_op.drop_index(batch_op.f('ix_mon_id'))

    op.drop_table('mon')
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_so_ban'))
        batch_op.drop_index(batch_op.f('ix_ban_id'))

    op.drop_table('ban')
    # ### end Alembic commands ###
